### ISSUE TITLE
Could not user SnapshotCollector 1.4.2 in production WebApp

### ISSUE THREAD

**Issue by alexmanie** [microsoft/ApplicationInsights-SnapshotCollector#19]
After adding Microsoft.ApplicationInsights.SnapshotCollector 1.4.2 to our AspNetCore project, .NET 5.0, the application could not start properly.

This is the Startup services configuration (just a part of it, for abbreviation):

<img width="835" alt="image" src="https://user-images.githubusercontent.com/8184686/152125516-24b53d53-c0aa-4813-8881-7864dcdcde49.png">

This is the error we can see on Application Event Logs:

`Application '/LM/W3SVC/649384701/ROOT' with physical root 'C:\home\site\wwwroot\' hit unexpected managed exception, exception code = '0xe0434352'. First 30KB characters of captured stdout and stderr logs:
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: telemetryProcessorTypedoes not implement ITelemetryProcessor.
   at Microsoft.Extensions.DependencyInjection.ApplicationInsightsExtensions.AddApplicationInsightsTelemetryProcessor(IServiceCollection services, Type telemetryProcessorType)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Microsoft.Extensions.DependencyInjection.SnapshotCollectorServiceCollectionExtensions.AddSnapshotCollector(IServiceCollection services, Action`1 configure)
   at Microsoft.Extensions.DependencyInjection.SnapshotCollectorServiceCollectionExtensions.AddSnapshotCollector(IServiceCollection services)
   at MyApi.Startup.ConfigureServices(IServiceCollection services) in D:\a\1\s\xxxxxxxx\Startup.cs:line 127
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at MyApi.Program.Main(String[] args) in D:\a\1\s\xxxxxxx\Program.cs:line 26

Process Id: 3616.
File Version: 15.0.21326.13. Description: IIS ASP.NET Core Module V2 Request Handler. Commit: 55738ff96b832439076e25584cfe0eb3bace9b01`

This is the scm /DiagnosticServices diagnostics:

<img width="719" alt="image" src="https://user-images.githubusercontent.com/8184686/152124976-ac44f783-93d6-4762-b427-368e0dc9405c.png">

How can we make it work ?
In local environments, no issues were found and the API is running perfectly.

These are the referenced packages and versions:

<TargetFramework>net5.0</TargetFramework>

<PackageReference Include="Microsoft.ApplicationInsights.AspNetCore" Version="2.20.0" />
<PackageReference Include="Microsoft.ApplicationInsights.SnapshotCollector" Version="1.4.2" />

Thanks in advance.

**Comment by pharring** [comment]
Thanks for the report, @alexmanie.
@renatosalas could you please take a look?

We have to use reflection to find the AddApplicationInsightsTelemetryProcessor method (so that it works in WorkerService and codeless scenarios), and I suspect we're selecting the wrong assembly.

@alexmanie I think you can work around this by replacing AddSnapshotCollector with:
```csharp
services.AddApplicationInsightsTelemetryProcessor<SnapshotCollectorTelemetryProcessor>();
```

**Comment by renatosalas** [comment]
Hi @alexmanie ,

Could you help us check what Application Insights SDK version ended up in your wwwroot folder inside Kudu, please?

Here are some docs to how to access to Kudu: https://docs.microsoft.com/azure/app-service/resources-kudu#access-kudu-for-your-app

You can download the Microsoft.ApplicationInsights.dll file from Kudu and open it using ILSpy tool (https://www.microsoft.com/p/ilspy/9mxfbkfvsq13)

The expected version of Application Insights SDK by Snapshot Collector is greater or equal than 2.15.0
![image](https://user-images.githubusercontent.com/5618127/152390628-e2822efd-ea2b-4440-a822-03c655ca4088.png)


If the version of the Application Insights SDK is different (< 2.15.0), maybe there might be some build process overridden that assembly, just to isolated old/stale assemblies, could you delete the wwwroot and re-deploy your app; make a clean deployment?

**Comment by alexmanie** [comment]
Hi @renatosalas ,
Micosoft.ApplicationInsights.dll seems to be the expected version 2.20.0.103

![image](https://user-images.githubusercontent.com/8184686/152493153-ee998223-f6bb-4c4d-afe2-791a89e9d4aa.png)

What else can I check ?

**Comment by alexmanie** [comment]
@renatosalas  @pharring  adding extended information from WebApp Diagnostic Services tool:

![image](https://user-images.githubusercontent.com/8184686/152494073-1fb8e051-875d-4676-81da-486cb0c3bd7b.png)

**Comment by renatosalas** [comment]
Hi @alexmanie,

Sorry for the delay, right now I'm working on building a repro scenario, I'm almost there, as soon as I completed, I can provide the resolution to you as simple as possible.

Expect later today my reply on this thread.

Thanks for your patience,
Renato

**Comment by renatosalas** [comment]
Hi @alexmanie ,

Thanks for your patience,

I was able to reproduce the issue when the "Interop" option was enabled and the Snapshot Collector SDK in your app was referenced; if you disable that option, everything should work as expected. Does this sounds the case; Interop enabled?

You can check by:
1. Go to your App Service resource (WebApp)
2. Select on the left side bar "Application Insights"
3. On the right page, select the ".NET Core" tab
4. Select "Off" option 

![image](https://user-images.githubusercontent.com/5618127/154168453-36432a88-6366-4888-8eac-a053c101df5c.png)

Before (current customer state)
![image](https://user-images.githubusercontent.com/5618127/154167979-1850e451-0d7a-4649-a7ba-f8164f9e589f.png)

After
![image](https://user-images.githubusercontent.com/5618127/154167993-088ba9ac-9bba-46f2-bca1-c96040a32c95.png) 



Let us know if that works for you and Snapshot Collector is working fine.

**Comment by alexmanie** [comment]
Hi @renatosalas , 

Thanks for your answer. I did it, combined with uninstalling "" from my source code project, and seems Snapshot Collector is currently properly configured as per Diagnostic Services:

![image](https://user-images.githubusercontent.com/8184686/154925176-1ba9924b-b14f-46bc-86c3-15970b852028.png)

Unfortunately, no Snapshots are seeing in the portal.
I did a troubleshoot to see what's happening, and I get that message:

![image](https://user-images.githubusercontent.com/8184686/154925217-1beef95c-96bc-4b93-936f-34157a3150ef.png)

How can I workaround with that?
As my application is an AspNet Core webapp, I don't have an ApplicationInsights.config file to modify.

Thanks in advance.

**Comment by aolszowka** [comment]
@alexmanie sorry to derail this; but I believe I am seeing similar behavior, can you tell me how you accessed the `scm /DiagnosticServices diagnostics` dialog in your screenshots so I can duplicate on my end?

**Comment by pharring** [comment]
@aolszowka please see: 
https://docs.microsoft.com/azure/azure-monitor/snapshot-debugger/snapshot-debugger-troubleshoot#check-the-diagnostic-services-site-extension-status-page
